[package]
name = "atra-controller"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
atra-id.workspace = true
atra-patch.workspace = true
atra-protocol.workspace = true
atra-store.workspace = true
atra-platform.workspace = true
base64.workspace = true
chrono.workspace = true
futures-util.workspace = true
http.workspace = true
indoc.workspace = true
rand.workspace = true
reqwest.workspace = true
os_info.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-rusqlite.workspace = true
tokio-util.workspace = true
tracing.workspace = true
webbrowser.workspace = true
tiktoken-rs.workspace = true
yaml-rust.workspace = true
zstd.workspace = true

[dev-dependencies]
atra-client.workspace = true
tempfile.workspace = true
