[package]
name = "atra-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "atra"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
atra-client.workspace = true
atra-controller.workspace = true
atra-platform.workspace = true
atra-protocol.workspace = true
atra-runner.workspace = true
atra-store.workspace = true
atra-tui.workspace = true
clap.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
toml.workspace = true
tracing-subscriber.workspace = true
xdg.workspace = true

[dev-dependencies]
tempfile.workspace = true
